name       : live-media
version    : 2022.02.07
release    : 4
source     :
    - http://www.live555.com/liveMedia/public/live.2022.02.07.tar.gz : 6f0c1f8a71ceb506bcbf969b02b4b0c3697b4e15daeb6dcba9872c8745ce92c6
homepage   : http://www.live555.com/
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : A set of C++ libraries for multimedia streaming
description: |
    A set of C++ libraries for multimedia streaming, using open standard protocols (RTP/RTCP, RTSP, SIP).
setup      : |
    sed -e 's/$(INCLUDES) -I. -O2 -DSOCKLEN_T/$(INCLUDES) -I. -O2 -I. -fPIC -DRTSPCLIENT_SYNCHRONOUS_INTERFACE=1 -DSOCKLEN_T/g' -i config.linux
    ./genMakefiles linux
build      : |
    %make PREFIX=/usr LIBDIR=%libdir%
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
