name       : live-media
version    : 2016.09.12
release    : 2
source     :
    - http://live555.com/liveMedia/public/live.2016.09.12.tar.gz : 09a046d0bf952291d4d70c26de4741ac11f049ee737592e6a251073cb3ecf9e0
license    : LGPL-2.1
component  : multimedia.library
summary    : A set of C++ libraries for multimedia streaming
description: |
    A set of C++ libraries for multimedia streaming, using open standard protocols (RTP/RTCP, RTSP, SIP).
setup      : |
    sed -e 's/$(INCLUDES) -I. -O2 -DSOCKLEN_T/$(INCLUDES) -I. -O2 -I. -fPIC -DRTSPCLIENT_SYNCHRONOUS_INTERFACE=1 -DSOCKLEN_T/g' -i config.linux
    ./genMakefiles linux
build      : |
    %make PREFIX=/usr LIBDIR=%libdir%
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
