name       : live-media
version    : 2023.07.24
release    : 6
source     :
    - http://www.live555.com/liveMedia/public/live.2023.07.24.tar.gz : 2e2225678f6284ade93ba8558dc5a3e53c844408fc1944571175369e060551ce
homepage   : http://www.live555.com/
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : A set of C++ libraries for multimedia streaming
description: |
    A set of C++ libraries for multimedia streaming, using open standard protocols (RTP/RTCP, RTSP, SIP).
environment: |
    # BasicTaskScheduler.cpp:191:40: error: 'struct std::atomic_flag' has no member named 'test'
    export CXXFLAGS="-std=c++20 $CXXFLAGS"
setup      : |
    sed -e 's/$(INCLUDES) -I. -O2 -DSOCKLEN_T/$(INCLUDES) -I. -O2 -I. -fPIC -DRTSPCLIENT_SYNCHRONOUS_INTERFACE=1 -DSOCKLEN_T/g' -i config.linux
    ./genMakefiles linux
build      : |
    %make PREFIX=/usr LIBDIR=%libdir%
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
