name       : live-media
version    : 2016.07.19
release    : 1
source     :
    - http://live555.com/liveMedia/public/live.2016.07.19.tar.gz : a86abfb8d0bdb04e2d0e1ae07de4eb03b8f4da899c1c28946f1fc6ace9624065
license    : LGPL
component  : programming.devel
summary    : A set of C++ libraries for multimedia streaming
description: |
    A set of C++ libraries for multimedia streaming, using open standard protocols (RTP/RTCP, RTSP, SIP).
builddeps  :
    - libgcc
setup      : |
    sed -e 's/$(INCLUDES) -I. -O2 -DSOCKLEN_T/$(INCLUDES) -I. -O2 -I. -fPIC -DRTSPCLIENT_SYNCHRONOUS_INTERFACE=1 -DSOCKLEN_T/g' -i config.linux
    $workdir/genMakefiles linux
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
